# Generated by Django 4.1.5 on 2023-01-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_service_short_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="service_name",
            field=models.CharField(max_length=255),
        ),
    ]
