# Generated by Django 4.1.5 on 2023-01-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_alter_service_service_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="service_name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="service",
            name="short_service",
            field=models.CharField(max_length=255),
        ),
    ]
